import type { AppState, Listing, TransportOffer, User } from '../types/models';

export const STORE_VERSION = 1;

const now = Date.now();
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString();

const users: User[] = [
  {
    id: 'u-landwirt',
    email: 'landwirt@demo.de',
    password: 'demo',
    displayName: 'Hof Sonnenwiese',
    role: 'landwirt',
    verified: true,
    ratingAvg: 4.8,
    ratingCount: 37,
    betriebsnummer: 'DE 09 1 234 5678',
    ort: 'Rosenheim',
    plz: '83022',
    createdAt: iso(-1000 * 60 * 60 * 24 * 400),
  },
  {
    id: 'u-haendler',
    email: 'haendler@demo.de',
    password: 'demo',
    displayName: 'Bayerische Viehvermarktung GmbH',
    role: 'haendler',
    verified: true,
    ratingAvg: 4.6,
    ratingCount: 212,
    betriebsnummer: 'DE 09 2 345 6789',
    ort: 'Landshut',
    plz: '84028',
    createdAt: iso(-1000 * 60 * 60 * 24 * 800),
  },
  {
    id: 'u-schlachthof',
    email: 'schlachthof@demo.de',
    password: 'demo',
    displayName: 'Regional-Schlachthof Allgäu',
    role: 'schlachthof',
    verified: true,
    ratingAvg: 4.4,
    ratingCount: 58,
    betriebsnummer: 'DE 09 3 456 7890',
    ort: 'Kempten',
    plz: '87435',
    createdAt: iso(-1000 * 60 * 60 * 24 * 600),
  },
  {
    id: 'u-hobby',
    email: 'hobby@demo.de',
    password: 'demo',
    displayName: 'Familie Berger',
    role: 'hobby',
    verified: false,
    ratingAvg: 5,
    ratingCount: 3,
    ort: 'Bad Tölz',
    plz: '83646',
    createdAt: iso(-1000 * 60 * 60 * 24 * 90),
  },
];

const listings: Listing[] = [
  {
    id: 'l-1',
    sellerId: 'u-landwirt',
    title: 'Milchkuh Fleckvieh, 2. Laktation',
    category: 'kuh',
    saleType: 'direktkauf',
    anzahl: 1,
    preis: 1450,
    beschreibung:
      'Gesunde Fleckvieh-Kuh aus Anbindehaltung mit Weidegang. Aktuell 28 l Tagesleistung, problemlos im Melkstand. Komplette Papiere vorhanden.',
    standortPlz: '83022',
    standortOrt: 'Rosenheim',
    imageEmoji: '🐄',
    hit: {
      ohrmarke: 'DE 09 123 45678',
      geburtsdatum: '2021-03-14',
      herkunftsbetrieb: 'Hof Sonnenwiese, Rosenheim',
      rasse: 'Fleckvieh',
      bvdStatus: 'unverdächtig',
      bhv1Status: 'frei',
      impfungen: [
        { bezeichnung: 'BVD', datum: '2024-04-02' },
        { bezeichnung: 'Rind­grippe (RSV/PI3)', datum: '2024-09-10' },
      ],
      vorbesitzerKette: ['Hof Sonnenwiese, Rosenheim'],
      abmeldungSimuliert: false,
    },
    createdAt: iso(-1000 * 60 * 60 * 24 * 2),
    status: 'aktiv',
  },
  {
    id: 'l-2',
    sellerId: 'u-haendler',
    title: '5 Fresser-Kälber, Schwarzbunt, ca. 80 kg',
    category: 'kalb',
    saleType: 'direktkauf',
    anzahl: 5,
    preis: 520,
    beschreibung:
      'Partie von 5 abgesetzten Fresser-Kälbern, alle enthornt, durchgeimpft und transportfähig. Preis pro Tier. Mengenrabatt ab Abnahme der gesamten Partie.',
    standortPlz: '84028',
    standortOrt: 'Landshut',
    imageEmoji: '🐮',
    hit: {
      ohrmarke: 'DE 09 234 11223',
      geburtsdatum: '2025-12-01',
      herkunftsbetrieb: 'Sammelstelle Landshut',
      rasse: 'Schwarzbunt (HF)',
      bvdStatus: 'unverdächtig',
      bhv1Status: 'frei',
      impfungen: [{ bezeichnung: 'Rind­grippe (RSV/PI3)', datum: '2026-01-15' }],
      vorbesitzerKette: ['Mehrere Erzeugerbetriebe', 'Sammelstelle Landshut'],
      abmeldungSimuliert: false,
    },
    createdAt: iso(-1000 * 60 * 60 * 24 * 1),
    status: 'aktiv',
  },
  {
    id: 'l-3',
    sellerId: 'u-landwirt',
    title: 'Zuchtbulle Fleckvieh, gekört, 18 Monate',
    category: 'bulle',
    saleType: 'auktion',
    anzahl: 1,
    beschreibung:
      'Gekörter Fleckvieh-Zuchtbulle mit sehr guten Exterieurnoten. Ruhiges Wesen, deckerprobt. Startgebot deutlich unter Marktwert.',
    standortPlz: '83022',
    standortOrt: 'Rosenheim',
    imageEmoji: '🐂',
    hit: {
      ohrmarke: 'DE 09 345 99887',
      geburtsdatum: '2024-11-20',
      herkunftsbetrieb: 'Hof Sonnenwiese, Rosenheim',
      rasse: 'Fleckvieh',
      bvdStatus: 'unverdächtig',
      bhv1Status: 'frei',
      impfungen: [{ bezeichnung: 'BVD', datum: '2025-06-01' }],
      vorbesitzerKette: ['Hof Sonnenwiese, Rosenheim'],
      abmeldungSimuliert: false,
    },
    auction: {
      startPreis: 1800,
      currentPreis: 2150,
      mindestSchritt: 50,
      endsAt: iso(1000 * 60 * 8), // endet in 8 Minuten
      status: 'live',
      bids: [
        {
          id: 'b-1',
          userId: 'u-haendler',
          userName: 'Bayerische Viehvermarktung GmbH',
          amount: 1900,
          timestamp: iso(-1000 * 60 * 20),
          isBot: true,
        },
        {
          id: 'b-2',
          userId: 'bot-2',
          userName: 'Zuchtbetrieb Huber',
          amount: 2050,
          timestamp: iso(-1000 * 60 * 9),
          isBot: true,
        },
        {
          id: 'b-3',
          userId: 'bot-3',
          userName: 'Milchhof Wegscheid',
          amount: 2150,
          timestamp: iso(-1000 * 60 * 3),
          isBot: true,
        },
      ],
    },
    createdAt: iso(-1000 * 60 * 60 * 24 * 3),
    status: 'aktiv',
  },
  {
    id: 'l-4',
    sellerId: 'u-haendler',
    title: '3 Schlachtkühe, Fleckvieh, Klasse R/O',
    category: 'kuh',
    saleType: 'direktkauf',
    anzahl: 3,
    preis: 1180,
    beschreibung:
      'Abgemolkene Schlachtkühe, gut bemuskelt, sofort schlachtreif. Lebendgewicht im Schnitt 720 kg. Preis pro Tier, Lieferung möglich.',
    standortPlz: '84028',
    standortOrt: 'Landshut',
    imageEmoji: '🐄',
    hit: {
      ohrmarke: 'DE 09 456 33445',
      geburtsdatum: '2018-05-09',
      herkunftsbetrieb: 'Sammelstelle Landshut',
      rasse: 'Fleckvieh',
      bvdStatus: 'unverdächtig',
      bhv1Status: 'frei',
      impfungen: [],
      vorbesitzerKette: ['Milchbetrieb Ostermünchen', 'Sammelstelle Landshut'],
      abmeldungSimuliert: false,
    },
    slaughter: {
      lebendgewichtKg: 720,
      handelsklasse: 'R',
      fettklasse: 3,
    },
    createdAt: iso(-1000 * 60 * 60 * 12),
    status: 'aktiv',
  },
  {
    id: 'l-5',
    sellerId: 'u-hobby',
    title: '2 Kälber zur Aufzucht – liebevoll aufgezogen',
    category: 'kalb',
    saleType: 'vermittlung',
    anzahl: 2,
    preis: 380,
    beschreibung:
      'Wir geben zwei zutrauliche Kälbchen aus Mutterkuhhaltung ab. Suchen ein gutes Plätzchen bei Hobbyhaltern oder kleinem Betrieb. Bei Fragen einfach melden – wir erklären gern alles.',
    standortPlz: '83646',
    standortOrt: 'Bad Tölz',
    imageEmoji: '🐮',
    hit: {
      ohrmarke: 'DE 09 567 22110',
      geburtsdatum: '2026-02-20',
      herkunftsbetrieb: 'Familie Berger, Bad Tölz',
      rasse: 'Murnau-Werdenfelser',
      bvdStatus: 'unverdächtig',
      bhv1Status: 'frei',
      impfungen: [],
      vorbesitzerKette: ['Familie Berger, Bad Tölz'],
      abmeldungSimuliert: false,
    },
    createdAt: iso(-1000 * 60 * 60 * 5),
    status: 'aktiv',
  },
  {
    id: 'l-6',
    sellerId: 'u-schlachthof',
    title: 'GESUCH: Schlachtbullen Klasse E/U, wöchentlich 10 Stück',
    category: 'bulle',
    saleType: 'gesuch',
    anzahl: 10,
    beschreibung:
      'Regional-Schlachthof Allgäu sucht laufend gut bemuskelte Schlachtbullen (EUROP E/U) aus der Region. Faire Tagespreise, schnelle Abholung mit eigenem Fuhrpark, prompte Bezahlung über Treuhand.',
    standortPlz: '87435',
    standortOrt: 'Kempten',
    imageEmoji: '🐂',
    hit: {
      ohrmarke: '—',
      geburtsdatum: '—',
      herkunftsbetrieb: 'gesucht',
      rasse: 'egal',
      bvdStatus: 'ungetestet',
      bhv1Status: 'ungetestet',
      impfungen: [],
      vorbesitzerKette: [],
      abmeldungSimuliert: false,
    },
    slaughter: {
      lebendgewichtKg: 700,
      handelsklasse: 'U',
      fettklasse: 3,
    },
    createdAt: iso(-1000 * 60 * 60 * 24 * 4),
    status: 'aktiv',
  },
  {
    id: 'l-7',
    sellerId: 'u-landwirt',
    title: 'Färse hochtragend, Fleckvieh, kalbt in 3 Wochen',
    category: 'faerse',
    saleType: 'auktion',
    anzahl: 1,
    beschreibung:
      'Hochtragende Färse, errechneter Kalbetermin in ca. 3 Wochen. Beste Abstammung, frei von BVD/BHV1. Auktion endet heute.',
    standortPlz: '83022',
    standortOrt: 'Rosenheim',
    imageEmoji: '🐄',
    hit: {
      ohrmarke: 'DE 09 678 55443',
      geburtsdatum: '2023-08-01',
      herkunftsbetrieb: 'Hof Sonnenwiese, Rosenheim',
      rasse: 'Fleckvieh',
      bvdStatus: 'unverdächtig',
      bhv1Status: 'frei',
      impfungen: [{ bezeichnung: 'BVD', datum: '2025-09-12' }],
      vorbesitzerKette: ['Hof Sonnenwiese, Rosenheim'],
      abmeldungSimuliert: false,
    },
    auction: {
      startPreis: 1600,
      currentPreis: 1750,
      mindestSchritt: 50,
      endsAt: iso(1000 * 60 * 25), // endet in 25 Minuten
      status: 'live',
      bids: [
        {
          id: 'b-4',
          userId: 'bot-4',
          userName: 'Milchhof Wegscheid',
          amount: 1650,
          timestamp: iso(-1000 * 60 * 30),
          isBot: true,
        },
        {
          id: 'b-5',
          userId: 'u-haendler',
          userName: 'Bayerische Viehvermarktung GmbH',
          amount: 1750,
          timestamp: iso(-1000 * 60 * 6),
          isBot: true,
        },
      ],
    },
    createdAt: iso(-1000 * 60 * 60 * 24 * 1),
    status: 'aktiv',
  },
];

const transportOffers: TransportOffer[] = [
  {
    id: 't-1',
    fahrerId: 'u-haendler',
    fahrerName: 'Viehtransporte Maier',
    zertifiziert: true,
    vonPlz: '83022',
    nachPlz: '87435',
    distanzKm: 120,
    fahrzeitMin: 95,
    preisEur: 180,
    maxTiere: 12,
    tierschutzKonform: true,
    status: 'angeboten',
  },
  {
    id: 't-2',
    fahrerId: 'bot-trans-2',
    fahrerName: 'AgrarLogistik Süd',
    zertifiziert: true,
    vonPlz: '84028',
    nachPlz: '83646',
    distanzKm: 75,
    fahrzeitMin: 65,
    preisEur: 130,
    maxTiere: 6,
    tierschutzKonform: true,
    status: 'angeboten',
  },
  {
    id: 't-3',
    fahrerId: 'bot-trans-3',
    fahrerName: 'Hof-zu-Hof Express',
    zertifiziert: false,
    vonPlz: '83646',
    nachPlz: '83022',
    distanzKm: 45,
    fahrzeitMin: 40,
    preisEur: 90,
    maxTiere: 4,
    tierschutzKonform: true,
    status: 'angeboten',
  },
];

export function createSeedState(): AppState {
  return {
    version: STORE_VERSION,
    users,
    currentUserId: null,
    listings,
    transportOffers,
    escrows: [],
    messages: [
      {
        id: 'm-1',
        threadId: 'u-hobby__u-landwirt',
        fromUserId: 'u-landwirt',
        toUserId: 'u-hobby',
        listingId: 'l-1',
        text: 'Grüß Gott! Die Kuh können Sie gern jederzeit besichtigen.',
        sentAt: iso(-1000 * 60 * 60 * 3),
        read: false,
      },
    ],
  };
}
